### PR TITLE
Revert "Relax overlinking errors because of compatibility issues"

### PR DESCRIPTION
**Pull request by ehfd**
Reverts conda-forge/libva-feedstock#37

### CODE REVIEW

**Comment by hmaarrfk** [comment]
in the future, we need a "build number bump" too...

**Comment by hmaarrfk** [comment]
please allow the bots to finish, before pressing merge, you are moving a little too fast.

While it is OK to sometimes break the rules, there is an "automerge" that would have allowed me 1 second to help by bumping the build number to 3.

**Comment by ehfd** [comment]
Ah, I kinda panicked a bit. I'll remember that.

**Comment by hmaarrfk** [comment]
honestly, its all cool, the problem seems that libxcb isn't listed in our global pinnings, so every feedstock is choosing a different minor version.

I need to patch up build 2 with the 1.15 restriction, then we can move to fixing the underlying problem.

**Comment by ehfd** [comment]
I think build 1 had a >=1.16,<1.17 restriction, that's what was the issue I think.

Also, I wonder why https://anaconda.org/conda-forge/libxcb and https://anaconda.org/search?q=libxcb show different versions...

**Comment by hmaarrfk** [comment]
its probably because other packages are pinned to 1.15 causing 1.15 to be the most downloaded version.

**Pull request merged**
