### PR TITLE
Relax overlinking errors because of compatibility issues

### PR DESCRIPTION
**Pull request by ehfd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
This is a counter-pattern for current recommendations, but because the ABI restrictions in libxcb are too strict, it fails to resolve with FFmpeg and many other cases. So we're reverting meta.yaml to what it was before.

**Comment by hmaarrfk** [comment]
Let's not do this and get to the source of the problem

**Comment by ehfd** [comment]
@hmaarrfk It was just because installations would blow up if the original version was kept any longer. I'm thinking of a way.

Edit: I just panicked because my PR might have blocked a package that gets >100000 downloads per version. I do feel that build 1 might have indeed been catastrophic, although the pinning could have just been manually updated.

```
Retrieving notices: ...working... done
Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package libva-2.21.0-h4ab18f5_1 requires libxcb >=1.16,<1.17.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ ffmpeg 7.0.1  is installable and it requires
│  └─ libxcb >=1.15,<1.16.0a0 , which can be installed;
└─ libva 2.21.0 *_1 is not installable because it requires
   └─ libxcb >=1.16,<1.17.0a0 , which conflicts with any installable versions previously reported.
```

```
Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package ffmpeg-6.0.1-gpl_h334edf3_100 requires libass >=0.17.1,<0.17.2.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ ffmpeg 6.0.1  is installable and it requires
│  └─ libass >=0.17.1,<0.17.2.0a0  with the potential options
│     ├─ libass 0.17.1 would require
│     │  └─ harfbuzz >=8.1.1,<9.0a0  with the potential options
│     │     ├─ harfbuzz [7.3.0|8.1.1|8.2.0|8.2.1] would require
│     │     │  ├─ cairo >=1.16.0,<2.0a0  with the potential options
│     │     │  │  ├─ cairo 1.16.0 would require
│     │     │  │  │  └─ icu >=58.2,<59.0a0 , which can be installed;
│     │     │  │  ├─ cairo 1.16.0 would require
│     │     │  │  │  └─ icu >=67.1,<68.0a0 , which can be installed;
│     │     │  │  ├─ cairo 1.16.0 would require
│     │     │  │  │  └─ icu >=68.1,<69.0a0 , which can be installed;
│     │     │  │  ├─ cairo 1.16.0 would require
│     │     │  │  │  └─ icu >=69.1,<70.0a0 , which can be installed;
│     │     │  │  ├─ cairo 1.16.0 would require
│     │     │  │  │  └─ libxcb >=1.13,<1.14.0a0 , which can be installed;
│     │     │  │  ├─ cairo 1.16.0 would require
│     │     │  │  │  └─ icu >=64.2,<65.0a0 , which can be installed;
│     │     │  │  └─ cairo [1.16.0|1.18.0] would require
│     │     │  │     └─ libxcb >=1.15,<1.16.0a0 , which can be installed;
│     │     │  └─ icu >=73.2,<74.0a0 , which conflicts with any installable versions previously reported;
│     │     └─ harfbuzz [8.3.0|8.4.0|8.5.0] would require
│     │        └─ cairo >=1.18.0,<2.0a0 , which can be installed (as previously explained);
│     └─ libass 0.17.1 would require
│        └─ harfbuzz >=7.2.0,<8.0a0  but there are no viable options
│           ├─ harfbuzz [7.2.0|7.3.0] would require
│           │  ├─ cairo >=1.16.0,<2.0a0 , which can be installed (as previously explained);
│           │  └─ icu >=72.1,<73.0a0 , which conflicts with any installable versions previously reported;
│           └─ harfbuzz [7.3.0|8.1.1|8.2.0|8.2.1], which cannot be installed (as previously explained);
└─ libva 2.21.0 *_1 is not installable because it requires
   └─ libxcb >=1.16,<1.17.0a0 , which conflicts with any installable versions previously reported.
```

**Comment by hmaarrfk** [comment]
> @hmaarrfk It was just because installations would blow up

I don't know what this means, please revert and open an issue wit ha reproducer that looks like

```
conda install --channel conda-forge --override-channels "libva>=YOUR_VERSION" "ffmpeg>=YOUR_VERSION"
```
and th error message for us to investigate.

**Pull request merged**
